config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'

  get 'home/about', to: 'homes#about'

  resources :books , only: [:create, :index, :show, :edit, :index, :update , :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users , only: [:show, :edit, :update, :edit, :index] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book
	validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
def create
	@book = Book.find(params[:book_id])
	comment = current_user.book_comments.new(book_comment_params)
	comment.book_id = @book.id
	comment.save
	redirect_to book_path(@book)
end
def destroy
	@book = Book.find(params[:book_id])
	comment = BookComment.find(params[:id])
	comment.destroy
	redirect_to book_path(@book)
end

private

def book_comment_params
	params.require(:book_comment).permit(:user_id,:comment)
end
def correct_user
    comment = current_user.book_comments.find_by(id: params[:id])
  	end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comments.html.erb
<table class="table">
  <% book.book_comments.each do |book_comment|%>
<tr>
  <td>
    <%= link_to attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg"), user_path(book_comment.user) %>
    <%= book_comment.user.name %>
  </td>
  <td>
    <%= book_comment.comment %>
  </td>

  <td>
    <% if book_comment.user_id == current_user.id %>
    <%= link_to "Delete", book_book_comment_path(book_comment.book.id,book_comment.id), method: :delete, class: "btn-sm btn-danger" %>
    <br>
    <% end %>
  </td>
</tr>
 <% end %>

 </table>