config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'

  get 'home/about', to: 'homes#about'

  resources :books , only: [:create, :index, :show, :edit, :index, :update , :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users , only: [:show, :edit, :update, :edit, :index] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy#1対Nの関係。アソシエーション。（モデル同士の紐付け）
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================
  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end
  validates :name, presence: true,  length: { minimum: 2, maximum: 20}#名前は2文字以上20文字以内。それ以外はエラーを表示。
  validates :introduction, length: { maximum: 50}#感想が50文字を超える場合はエラーを表示。
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def new#新しい本の投稿の指示
        @book = Book.new
  end

  def show#home画面の表示の指示
    @book = Book.new#新しい本の投稿の表示
  	@user = User.find(params[:id])#投稿したuserを区別する為のカラム（id）の振り分け。
    @books = @user.books#本の投稿とゆう@booksインスタンス変数に@userの投稿したbooks情報を代入して表示させる。
  end


  def edit#booksのeditに遷移する。
       @user = User.find(params[:id])#投稿したuserを区別する為のカラム（id）の振り分け。
    if @user != current_user#もしログイン済のuserが編集に成功したら？
      redirect_to user_path(current_user.id)#booksのshowに遷移する。
    end
  end

  def update#投稿した情報の編集に成功した場合の挙動
  	@user = User.find(params[:id])#投稿したuserを区別する為のカラム（id）の振り分け。
    if @user.update(user_params)#もし投稿の編集に成功し、情報の更新に成功したら？
    flash[:notice] = "You have creatad book successfully."#成功した場合のサクセスメッセージ表示の構文。
    redirect_to user_path(@user.id)#成功した場合の遷移ページ先。
    else
    flash[:notice] = "error prohibited this obj from being saved"#失敗した場合のエラーメッセージの構文。
    render :edit#投稿に失敗した場合の遷移ページの指定。renderとredirect_toの違いについてはbooks_controllerbのメモを参照。
    end
end
  def index#user一覧の参照。
    @user = current_user#ログイン済のuserの一覧ページの表示。
    @book = Book.new#booksの新規投稿の情報を表示。
    @users = User.all#一覧ページ（usersのindexページ！）にuserのの投稿データの全てを表示＊＠マークのついているインスタンス変数はviewページに表示。
  end
  #＝＝＝＝＝＝＝＝＝＝＝フォロー関係追加===========
  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
  #＝＝＝＝＝＝＝＝＝＝＝フォロー関係追加===========
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_list.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>
<h2>User info</h2>
<%= attachment_image_tag @user, :profile_image, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg", size: "100x100" %>
<table class="table">
  <tbody>
    <tr>
        <th>name</th>
        <th><%= @user.name %></th>
    </tr>
    <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th><%=link_to @user.followings.count, follows_user_path(@user.id) %></th>
    </tr>

    <tr>
      <th>followers</th>
      <th><%=link_to @user.followers.count, followers_user_path(@user.id) %></th>
    </tr>
    <tr>
    <tr>
    </tbody>
</table>

    <h2>New book</h2>
    <%= form_for (book) do |f| %>

    <div class="field row">
    <h4>Title</h4>
    <%= f.text_field :title, class: "col-xs-12 book_title"%>
  </div>

    <div class="field row">
    <h4>Opinion</h4>

    <%= f.text_area :body, class: "col-xs-12 book_body" %>
  </div>
  <div class="actions row">
   <%= f.submit 'Create Book',class: "btn btn-primary col-xs-12"%>
  </div>
   <% end %>

app/views/users/edit.html.erb
<h1>User info</h1>

<%= form_for(@user) do |f| %>
<% if @user.errors.any? %>
  <h2><%= @user.errors.count %>error prohibited this obj from being saved:</h2>
  <ul><% @user.errors.full_messages.each do |messages| %></ul>
    <li><%= messages %></li>
  <% end %>
  <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: "name" %>
    </div>

    <label for="Image">Image</label>
    <%= f.attachment_field :profile_image  %>
  </div>

  <div class="field">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: "introduction" %>
  </div>



  <div class="actions">
    <%= f.submit "Update User" %>
  </div>
<% end %>

app/views/users/followers.html.erb
<h1>Followers Users</h1>
<table class="table">
            <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
<% @users.each do |user| %>
                <tr>
                  <td>
                    <a><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "60x60" %></a><!--イメージ画像のコード-->
                  </td>
                  <td><%= user.name %></td>
                  <td><p>フォロー数：<%= user.followings.count %></p></td><!--フォロー数のカウント下記も同じ-->
                  <td><p>フォロワー数：<%= user.followers.count %></p></td>
                  <td><%= link_to "Show", user_path(user.id) %></td><!--show画面への遷移-->
<% end %>
</tbody>
</table>

app/views/users/follows.html.erb
<h1>Follow Users</h1>
<table class="table">
            <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
<% @users.each do |user| %>
<tr>
    <td>
      <a><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "60x60" %></a><!--イメージ画像のコード-->
    </td>
    <td><%= user.name %></td>
                  </tr>
    <% if current_user != user %>
        <% if user.followed_by?(current_user) %>
            <p><%=link_to "フォロー済み", user_relationships_path(user.id), method: :delete %></p>
        <% else %>
            <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
        <% end %>
    <% end %>
<% end %>
</tbody>
</table>

app/views/users/index.html.erb
    <div class="container">
    <div class="row">
    <div class="col-xs-3">
          <%= render 'users/list' ,user: @user,book:@book %>
    </div>
    <div class="col-xs-9">
          <h2>Users</h2>
          <table class="table">
            <thead>
            <tr>
              <th>Image</th>
              <th>Name</th>
              <th colspan="3"></th>
            </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr>
                  <td>
                    <a><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "60x60" %></a><!--イメージ画像のコード-->
                  </td>
                  <td><%= user.name %></td>
                  <td><p>フォロー数：<%= user.followings.count %></p></td><!--フォロー数のカウント下記も同じ-->
                  <td><p>フォロワー数：<%= user.followers.count %></p></td>

                  <% if current_user != user %>
                  <!--ログイン済みのユーザーである場合-->
                  <% if user.followed_by?(current_user) %><!-- ログイン済みのユーザーがフォロー-->
                  <td><%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete %></td>
              <% else %>
                  <td><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
              <% end %>
              <% end %>
                  <td><%= link_to "Show", user_path(user.id) %></td><!--show画面への遷移-->
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

app/views/users/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
  <% end %>
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h2>User info</h2>
    <table class="table">
  <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "100x100" %>
    <tbody>
    <tr>
        <th>name</th>
        <th><%= @user.name %></th>
    </tr>
    <tr>
        <th>introduction</th>
        <th><%= @user.introduction %></th>
    </tr>
    <tr>
      <th>
        <p>follows</p>
     <th><%=link_to @user.followings.count, follows_user_path(@user.id) %><th>
    </tr>

    <tr>
      <th>followers</th>
      <th><%=link_to @user.followers.count, followers_user_path(@user.id) %></th>
    </tr>
     <% if current_user != @user %>
                  <!--ログイン済みのユーザーである場合-->
     <% if @user.followed_by?(current_user) %>
     <td><%=link_to "フォロー解除", user_relationships_path(@user.id), method: :delete %></td>
              <% else %>
     <td><%=link_to "フォローする", user_relationships_path(@user.id), method: :post %></td>
     <% end %>
     <% end %>
  </tbody>
</table>


    <h2>New book</h2>
    <%= form_for (@book) do |f| %>


    <div class="field row">
    <h4>Title</h4>
    <%= f.text_field :title, class: "col-xs-12 book_title"%>
  </div>

    <div class="field row">
    <h4>Opinion</h4>

    <%= f.text_area :body, class: "col-xs-12 book_body" %>
  </div>
  <div class="actions row">
   <%= f.submit 'Create Book',class: "btn btn-primary col-xs-12"%>
  </div>
   <% end %>
   </div>
    <div class="col-xs-9">
      <h3>Books</h3>
      <table class="table table-striped">
        <thead>
        <tr>
          <th>Title</th>
          <th>Opinion</th>
          <th colspan="3"></th>
        </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to  user_path(@user.id) do %>
                <%= attachment_image_tag @user, :profile_image, class: "img-circle pull-left profile-thumb", fallback: "no_image.jpg", size: "60x60" %>
              <% end %>
            </td>
            <td>
              <%= link_to book.title, book_path(book) %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>