config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homes#top'

  get 'home/about', to: 'homes#about'

  resources :books , only: [:create, :index, :show, :edit, :index, :update , :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users , only: [:show, :edit, :update, :edit, :index] do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member # 追加
    get :followers, on: :member # 追加
  end
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	validates :title, presence: true
	validates :body, presence: true, length: { maximum: 200}
	def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
    def create#投稿系の指示！！
  	 @book = Book.new(book_params)#新しい本の投稿の指示+新規投稿呼び出しの指示（idはbook paramsから所得）
     @book.user_id = current_user.id#current_user_idはログイン済みのこと。←空のユーザーの本の投稿情報にログイン済みのユーザーが投稿情報を入れる。
    if @book.save#もし本の投稿に成功したら？
     flash[:notice] = "You have creatad book successfully."#成功した場合成功のメッセージ
     redirect_to book_path(@book.id)#投稿が成功した場合の遷移ページの指定。←この場合はbooksのshowページに遷移している。idの確認の仕方はrails rotuesで確認。
    else#投稿が成功しなかったら
      @books = Book.all#投稿した全てのbooksの情報をブックスモデルから呼び出す。
      @user = current_user#ログイン済みのユーザーの情報を@userインスタンス変数に代入し表示

        flash[:error] = "1 error prohibited this obj from being saved:Body can't be blank"#もし失敗した場合のエラーメッセージ
        render :index#失敗した場合の遷移先。renderとredirect_toの違いは・renderは表示させるviewファイルを指定（showやindexなど。）・redirect_toはURL(HTTPリクエストメソッド＝パスね）を指定
    end

end
   def index#一覧ページ！！
    @user = current_user#ログイン済みのユーザーの一覧ページを表示。何度も言うがcurrent_userはログイン済みのユーザーである。
  	@books = Book.all#一覧ページ（booksのindexページ！）に本の投稿データの全てを表示＊＠マークのついているインスタンス変数はviewページに表示。
  	@book = Book.new#本の新規投稿の情報を一覧ページ（booksのindexページ！）に表示
end

  def show#投稿した本の詳細ページ。
  	 @book = Book.find(params[:id])#投稿した本を区別する為のカラム（id）の振り分け。
     @user = @book.user#←読み下し→このユーザーのこの本の（ユーザーの本のインスタンス変数）情報をユーザーのインスタンス変数に代入し表示。（@book.userの読み下しはユーザーが代入したい本の情報）
     @new_book = Book.new#新しい本のインスタンス変数の中に投稿したい本のローカル変数を代入し表示。
     @book_comment = BookComment.new
     @book_comments = @book.book_comments
  end


  def edit#投稿した情報の編集ページ（book!!）
  	@book = Book.find(params[:id])#投稿した本を区別する為のカラム（id）の振り分け。
    if @book.user_id != current_user.id#もしログイン済みのユーザーが情報の編集に成功したら
     redirect_to books_path#booksのeditページに遷移する
   end
   end

  def update#情報の更新
  	@book = Book.find(params[:id])#投稿した本を区別する為のカラム（id）の振り分け。
    @book.user_id = current_user.id#もしログイン済みのユーザーが情報の更新に成功したら
if  @book.update(book_params)#もし本の再投稿に成功したら？
    flash[:notice] = "You have creatad book successfully."
  	redirect_to book_path(@book.id)#成功した場合booksのindexに遷移する。
   else
    flash[:notice] = "1 error prohibited this obj from being saved"
       render :edit#編集に失敗した場合現在のページにとどまる。
  end
end


  def destroy
  	@book = Book.find(params[:id])#投稿した本を区別する為のカラム（id）の振り分け。
  	@book.destroy#投稿した情報（投稿したbookのインスタンス変数）を削除する指示。
  	redirect_to books_path#削除に成功した場合booksの一覧（index)に遷移する。
  end

private#境界線。ここから下はcontrollerの中でしか呼び出せませんという意味があります。そのため、他のアクション（index,show,createなど）を巻き込まないようにprivateはControllerファイルの一番下のendのすぐ上に書いて下さい。

   def book_params
	params.require(:book).permit(:title, :body)
end
end
#@のついたインスタンス変数とローカル変数の違いは@のついているインスタンス変数はビューファイルへ受け渡すことができます。
#一方でローカル変数は、ビューファイルに受け渡しができません。アクション内でしか利用できません。今回はビューファイルへの受け渡しが必要ではないため、ローカル変数を利用しています。インスタンス変数でも同様の処理はできますが、無駄に利用できる範囲が広い変数は、今後、沢山の変数を利用するようになった際、不具合が起きやすい原因になります。
#これで、フォームからデータを受け取りデータベースへ保存できる形ができました。

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="center-block">
<div class="container">
<div class="row">
<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>

<% if @book.errors.any? %>
  <h2><%= @book.errors.count %>error prohibited this obj from being saved:</h2>
  <ul><% @book.errors.full_messages.each do |messages| %></ul>
    <li><%= messages %></li>
  <% end %>
<% end %>
  <h4>Title</h4>
  <div class="field">
    <%= f.text_field :title, :size => "50*50" %>
  </div>
  <div class="field">
  <h4>Opinion</h4>
    <%= f.text_area :body, :size => "50*50" %>
  </div>

  <div class="actions row">
   <%= f.submit 'Update Book',class: "btn btn-primary"%>
  </div>
  <% end %>

<%= link_to "Show", book_path %>
<%= link_to "Back", books_path %>
</div>
</div>
</div>

app/views/books/index.html.erb
<div class="container">
  <div class="row">
    <% if @book.errors.any? %>
      <%= @book.errors.count %>件のerrorが発生しました
      <% @book.errors.full_messages.each do |message| %>
        <%= message %>
      <% end %>
    <% end %>
   </div>
  <div class="row">
  <div class="col-xs-3">
    <%= render 'users/list' ,book: @book %>
    </div>
    <div class="col-xs-9">
      <h2>Books</h2>
      <table class="table table-striped">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <%= link_to user_path(book.user.id) do %>
            <tr>
              <td>
                <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "60x60" %>
                <% end %>
              </td>
              <td>
                <%= link_to book.title, book_path(book.id) %>
              </td>
              <td><%= book.body %></td>
              <!--以下いいね機能の実装-->
              <% if book.favorited_by?(current_user) %>
              <td>
              <%= link_to book_favorites_path(book), method: :delete do %>
                <i class="fa fa-heart" aria-hidden="true"></i>
              <%= book.favorites.count %>
              <% end %>
            </td>
            <% else %>
            <td>
                <%= link_to book_favorites_path(book), method: :post do %>
                <i class="fa fa-heart-o" aria-hidden="true"></i>
                <%= book.favorites.count %>
                <% end %>
            </td>
            <% end %>

            <td>
              <!--以下コメント機能の実装-->
            <%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %>
            </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
  <p><%= flash[:notice] %></p>
<% end %>
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<%= render 'users/list', book: @new_book, user: @user %>
		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>
			<table class="table table-striped">
				<tbody>
					<tr>
					<td>
            <%= link_to user_path(@user.id) do %>
              <%= attachment_image_tag @user, :profile_image,  fallback: "no_image.jpg", size: "60x60" %>
              <%= @user.name %>
            <% end %>
					</td>
					<td>
					  <%=  @book.title  %>
					</td>
					<td>
					  <%= @book.body %>
					</td>
					<td>

            <% if @book.user_id == current_user.id %>
					    <%= link_to "Edit", edit_book_path(@book.id) ,class:"btn-sm btn-success edit_book_10349" %>
					    <%= link_to "Destroy", book_path(@book.id), method: :delete,  "data-confirm" => "本当に削除しますか？"  ,class:"btn-sm btn-danger destroy_book_10349"%>
				    <% end %>
					</td>
					</tr>
				</tbody>
			</table>
			<!--以下コメント機能実装-->
			<%= form_for [@book, @book_comment] do |f| %>
  <div class="row">
    <div class="col-sm-12">
      <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
    </div>
  </div>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
  <%= render 'book_comments/comments', book: @book %>
<% end %>
		</div>
	</div>
</div>